# Kalilix Development Session
# tmuxp session configuration for polyglot development
# Usage: tmuxp load .tmuxp.yaml

session_name: kalilix
start_directory: ./

windows:
  # 🚀 Home Window 📸
  - window_name: "🚀 Kalilix"
    layout: main-horizontal
    options:
      main-pane-height: 66% # Top panes take up 2/3 of window
    focus: true
    panes:
      # Top: Neovim with README on left and ClaudeCode integration on right
      - focus: true
        shell_command:
          - nvim README.md # -c "ClaudeCodeOpen" -c "wincmd h"
          # Opens README, ClaudeCode opens in a split automatically, focus back to README

      # Bottom: Full-width task list
      - shell_command:
          - mise task ls
# # Nix operations window
# - window_name: Ops
#   layout: even-vertical
#   panes:
#     - shell_command:
#         - mise task ls

# # Docker/Container window
# - window_name: Docker
#   panes:
#     - shell_command:
#         - docker ps --all

# # Shell for ad-hoc commands
# - window_name: Bash
#   panes:
#     - shell_command:
#         - hyfetch
#         - mise run status
