# Kalilix Systemd-Powered Development Environment
# Production-grade containerized development with multi-user Nix daemon
#
# Primary Usage:
#   docker compose up                   # Starts systemd devcontainer
#   docker compose up -d                # Starts in background with systemd
#   docker compose down                 # Graceful systemd shutdown
#
# Service Control:
#   docker compose ps                   # List running services
#   docker compose logs devcontainer    # View systemd journal
#   docker compose exec devcontainer systemctl status    # Check systemd services
#   docker compose exec -u debian devcontainer bash      # User shell access
#
# Advanced Usage:
#   docker compose build --no-cache devcontainer         # Rebuild from scratch
#   docker compose exec devcontainer journalctl -xef     # Follow system logs

name: kalilix

include:
  # Systemd-based devcontainer is now the only supported configuration
  - path: .devcontainer/compose/systemd.yml

networks:
  # Primary infrastructure network for all platform services
  kalilix: 
    name: kalilix-workspace
    driver: bridge
    ipam:
      config:
        - subnet: 10.15.0.0/24
          gateway: 10.15.0.1

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
    labels: "com.kalilix.workspace.service"

x-healthcheck-defaults: &default-healthcheck
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 40s

x-service-defaults: &service-defaults
  restart: unless-stopped
  logging: *default-logging
  labels:
    com.kalilix.workspace.managed: "true"
    com.kalilix.workspace.environment: "${ENVIRONMENT:-development}"
# secrets:
#   postgres_password:
#     file: ./secrets/postgres_password.txt
#   jwt_secret:
#     file: ./secrets/jwt_secret.txt
#   api_keys:
#     file: ./secrets/api_keys.json

# configs:
#   nginx_conf:
#     file: ./config/nginx/nginx.conf
#   prometheus_yml:
#     file: ./config/prometheus/prometheus.yml
