#cloud-config
hostname: kalilix
fqdn: kalilix.home.arpa
ssh_pwauth: true
disable_root: false
chpasswd:
  list: |
    root:kc2admin
    kali:kali
  expire: False
users:
  - default
  - name: kali
    gecos: Kalilix Development User
    shell: /bin/bash
    lock_passwd: false
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    groups: adm,cdrom,dip,sudo,docker
growpart:
  mode: auto
  devices: ["/"]
  ignore_growroot_disabled: true
timezone: UTC
package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
  - vim
  - git
  - curl
  - jq
  - build-essential
  - qemu-guest-agent
  - docker.io
  - docker-compose
runcmd:
  - chown -R kali:kali /home/kali
  - chmod 700 /home/kali/.ssh
  - chmod 600 /home/kali/.ssh/authorized_keys
  - chown kali:kali /home/kali/.ssh/authorized_keys
  - systemctl enable --now qemu-guest-agent
  - sleep 4
  - systemctl restart qemu-guest-agent
  - systemctl enable --now docker
  - systemctl restart docker
  - usermod -aG docker kali
  - sudo -u kali bash -c 'curl https://mise.run | sh'
  - sudo -u kali git clone -b feat/kubevirt-bootstrap https://github.com/scopecreep-zip/kalilix.git /home/kali/.kalilix
  - sudo -u kali bash -c 'cd /home/kali/.kalilix && /home/kali/.local/bin/mise trust /home/kali/.kalilix'
  - sudo -u kali bash -c 'cd /home/kali/.kalilix && /home/kali/.local/bin/mise trust /home/kali/.kalilix/.config'
  - sudo -u kali bash -c 'cd /home/kali/.kalilix && /home/kali/.local/bin/mise trust /home/kali/.kalilix/.config/mise'
  - sudo -u kali bash -c 'cd /home/kali/.kalilix && /home/kali/.local/bin/mise trust /home/kali/.kalilix/.config/mise/toml'
  - sudo -u kali bash -c 'cd /home/kali/.kalilix && /home/kali/.local/bin/mise trust /home/kali/.kalilix/.config/mise/tasks'
  - sudo -u kali bash -c 'export PATH="/home/kali/.local/bin:$PATH" && cd /home/kali/.kalilix && mise run bootstrap'
  - sudo -u kali bash -c 'cd /home/kali/.kalilix && source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh && nix develop .#full --command true'
  - sudo -u kali bash -c 'echo "export PATH=\"\$HOME/.local/bin:\$PATH\"" >> /home/kali/.bashrc'
  - sudo -u kali bash -c 'echo "[ -f /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ] && source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh" >> /home/kali/.bashrc'
  - |
    cat > /etc/motd <<'EOF'
    ╔═══════════════════════════════════════════════════════════╗
    ║                                                           ║
    ║              Kalilix Development Environment              ║
    ║              Ubuntu 24.04 with Lix/Nix Flakes             ║
    ║                                                           ║
    ║  User: kali                                               ║
    ║  Kalilix: ~/.kalilix/                                     ║
    ║                                                           ║
    ║  Quick Start:                                             ║
    ║    cd ~/.kalilix                                          ║
    ║    mise run status      # Check environment               ║
    ║    nix develop          # Enter base shell                ║
    ║    nix develop .#python # Enter Python shell              ║
    ║                                                           ║
    ╚═══════════════════════════════════════════════════════════╝
    EOF

  - echo "$(date) - Kalilix bootstrap complete" > /home/kali/kalilix-bootstrap-complete
  - chown kali:kali /home/kali/kalilix-bootstrap-complete

final_message: "Kalilix development environment ready after $UPTIME seconds"
